### ISSUE TITLE
不明白Step4具体如何操作

### ISSUE THREAD

**Issue by HaoyunHong** [saturn-lab/androidAudioRecg#1]
Step 4 `Run Tensorflow inference interface` 具体如何操作

**Comment by zhenchen3419** [comment]
tensorflow的底层Inference库，用C++写的，编译为 *.so文件。
android系统调用inference库interface的java包，编译为*.jar文件。

**Comment by zhenchen3419** [comment]
Android TensorFlow support:  https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android
