### ISSUE TITLE
Upgrade AudioRecg to higher Android SDK!

### ISSUE THREAD

**Issue by zhenchen3419** [saturn-lab/androidAudioRecg#4]
Upgrade to higher version of SDK.

**Comment by LGXNOTLGX** [comment]
提供两种解决方法
1. 降低Android SDK的版本，在本实验中，使用的代码的SDK版本过高，使用的是25.03，此版本市场占有率为4%，可以降低代码的SDK版本来运行，具体操作是在cmake/src/build.gradle这个文件中修改compileSdkVersion和buildToolsVersion两个参数，必要时还需修改minSdkVersion的版本，具体的版本参照自己安装的SDK进行选择，查看自己的SDK的方法：Tools->Android->SDK Manger
2.提高自己Android Studio的SDK版本，打开SDK Manger 进行下载Android-25的版本，因为cmake的文件是引用现在的tensorflow仓库的cmake文件，所以可能会发生改变，具体的版本参照build.gradle中的要求
注：如没有SDK Manger，可以等待Android Studio 自行下载，也可以从官网下载

**Comment by LGXNOTLGX** [comment]
提供两种解决方法
1. 降低Android SDK的版本，在本实验中，使用的代码的SDK版本过高，使用的是25.03，此版本市场占有率为4%，可以降低代码的SDK版本来运行，具体操作是在cmake/src/build.gradle这个文件中修改compileSdkVersion和buildToolsVersion两个参数，必要时还需修改minSdkVersion的版本，具体的版本参照自己安装的SDK进行选择，查看自己的SDK的方法：Tools->Android->SDK Manger
2. 提高自己Android Studio的SDK版本，打开SDK Manger 进行下载Android-25的版本，因为cmake的文件是引用现在的tensorflow仓库的cmake文件，所以可能会发生改变，具体的版本参照build.gradle中的要求
注：如没有SDK Manger，可以等待Android Studio 自行下载，也可以从官网下载
